In [1]:
import numpy as np
import pandas as pd

In [2]:
train=pd.read_csv("cleaned_titanic1.csv")
test=pd.read_csv("cleaned_titanic2.csv")

In [3]:
train.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0
3         1       1    1  35.0      1      0  53.1000         0
4         0       3    0  35.0      0      0   8.0500         0

In [4]:
test.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  34.5      0      0   7.8292         2
1       3    1  47.0      1      0   7.0000         0
2       2    0  62.0      0      0   9.6875         2
3       3    0  27.0      0      0   8.6625         0
4       3    1  22.0      1      1  12.2875         0

## Create FamilySize Feature

In [5]:
train["FamilySize"] = train["SibSp"] + train["Parch"] + 1
test["FamilySize"] = test["SibSp"] + test["Parch"] + 1

In [7]:
train["IsAlone"] = 0
train.loc[train["FamilySize"] == 1, "IsAlone"] = 1

test["IsAlone"] = 0
test.loc[test["FamilySize"] == 1, "IsAlone"] = 1

In [8]:
train.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,FamilySize,IsAlone
0,0,3,0,22.0,1,0,7.2500,0,2,0
1,1,1,1,38.0,1,0,71.2833,1,2,0
2,1,3,1,26.0,0,0,7.9250,0,1,1
3,1,1,1,35.0,1,0,53.1000,0,2,0
4,0,3,0,35.0,0,0,8.0500,0,1,1

## now we can drop
## SibSp
## Parch

In [9]:
train.drop(["SibSp","Parch"], axis=1, inplace=True)
test.drop(["SibSp","Parch"], axis=1, inplace=True)

# feature scaling

In [10]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
numerical_cols= ["Age","Fare","FamilySize"]
train[numerical_cols] = scaler.fit_transform(train[numerical_cols])
test[numerical_cols] = scaler.transform(test[numerical_cols])

In [11]:
X = train.drop("Survived", axis=1)
y = train["Survived"]